### PR TITLE
Feature3 is added in the README file

### LINKED ISSUE #2: **Cards**
Cards can be added to your board to track the progress of issues and pull requests. You can also add note cards, like this one!

### PR DESCRIPTION
**Pull request by marcelkarlsons**
This is a text to describe the feature 3 more

### CODE REVIEW

**Review by maenmulhem — COMMENTED** [review]
We need to change something

**Review by marcelkarlsons — COMMENTED** [review]
Look at it carefully

**Review by maenmulhem — CHANGES_REQUESTED** [review]
Consider the style

**Review by maenmulhem — APPROVED** [review]
Feature3 works well now

**Pull request merged**
